### PR TITLE
Pin flake8 and friends to reduce code analysis errors

### PR DESCRIPTION
**Pull request by hvelarde**

### CODE REVIEW

**Comment by idgserpro** [comment]
Ate these the latest versions of `flake8-*` to make it compatible with `flake8 = 3.x`? It would be nice to have a simple `.travis.yml` job here to test against multiple Plone versions to see if something breaks. We made a simple test in https://travis-ci.org/plonegovbr/brasil.gov.portal/jobs/259862752 using these pins and it seems ok, but we're not so sure about 4.1 and 4.2 installations that may be using qa.cfg.

Isn't this overkill? Shouldn't we just pin flake8? We already pin a bunch of `flake8-*` ourselves (https://github.com/plonegovbr/portalpadrao.release/blob/667be79173b74fd3f3f4f295d7453d7c5f727db1/1.1.5.3/versions.cfg#L66), but only because we still have `flake8 = 2.4.1`.

**Comment by hvelarde** [comment]
@idgserpro I'm doing this because of this: https://travis-ci.org/collective/sc.social.like/builds/259762263

**Comment by idgserpro** [comment]
Did you try to pin just flake8 to 3.3.0? Why do you need to pin all packages in flake8-* namespace? All of them ask for setuptools > = 30? We did a test just pinning flake8 and it worked so far in https://travis-ci.org/collective/sc.social.like/builds/259951378

Nevertheless, we would pin just flake8 and the following documentation above the pin:

```
# This is the last flake8 version that don't ask for setuptools >= 30. 
# We want to avoid problems with Plone 4.3.x branch, since at the time of this pinning was asking for setuptools 26.1.1 in http://dist.plone.org/release/4.3-latest/versions.cfg
# Avoids "Error: The requirement ('setuptools>=30') is not allowed by your [versions] constraint (26.1.1)"
```

**Comment by mauritsvanrees** [comment]
Pinning `flake8` should be enough, and can indeed be helpful. 👍 

If we pin everything here, the danger is always that no one adjusts this list for a couple of months, and we miss out on QA improvements. The same is true in `bobtemplates.plone_addon`, where theses same packages are pinned, but several of them are older versions than you have.

A `.travis.yml` in this repository to test the basic usage could be helpful yes, though that is of course outside of the range of this pull request.

**Pull request merged**
