### PR TITLE
Set newest = false to avoid endless restarting loops while running buildout

### PR DESCRIPTION
**Pull request by hvelarde**
The issue can be seen here: https://travis-ci.org/collective/collective.liveblog/jobs/448559118#L1562

### CODE REVIEW

**Comment by hvelarde** [comment]
@mauritsvanrees I'm not pretty sure if we must add this on `test` or on `plone` configurations; what do you think?

**Comment by idgserpro** [comment]
Did you try:

```bash
pip uninstall -y setuptools
```
?

**Comment by idgserpro** [comment]
@hvelarde I saw that even with python without setuptools the problem happens. It may be best to install the version of setuptools with pip.

**Comment by idgserpro** [comment]
@mauritsvanrees  willn't that make new versions stop being downloaded? I think that's bad for CI.

**Comment by idgserpro** [comment]
@hvelarde with a [clean site-packages](https://github.com/collective/collective.liveblog/blob/setuptools/.travis.yml#L17) the buildout works. See:

https://travis-ci.org/collective/collective.liveblog/jobs/449910618

**Comment by hvelarde** [comment]
that's kind of a hack :)

**Comment by idgserpro** [comment]
@hvelarde yes it's a hack. But at least it's not necessary to freeze the packages versions.

Another option is install the correct version of setuptools with pip:

```
pip install setuptools==39.1.0
```

**Comment by idgserpro** [comment]
@hvelarde see:

https://travis-ci.org/collective/collective.liveblog/jobs/451400339#L450

**Comment by hvelarde** [comment]
@idgserpro we have currently many packages failing because of this; the fact is the current state of things makes my life miserable because I'm the one who has to fix that.

setting `newest = false` don't avoid using newer versions when available **and pinned**; that's the case with newer Plone versions.

leaving things as they are now creates a lot of unexpected issues all over the place.

**Pull request merged**
