### PR TITLE
use pytest besides testrunner

### PR DESCRIPTION
**Pull request by gotcha**
Let's run tests with pytest.

By using `gocept.pytestlayer`, we can run tests with `zope.testing` layers.

### CODE REVIEW

**Comment by idgserpro** [comment]
Just out of curiosity, what's the advantage/motivation of adding pytest since we can run tests without it?

**Comment by gotcha** [comment]
pytest is a living project and it is very pythonic and feature full. While Zope test runner is not.

**Comment by tisto** [comment]
I am not actively involved in buildout.plonetest and I never used it. My 2c anyways: adding pytest as an option is definitely a good addition. pytest is an awesome project and the de-facto standard for testing with Python. I fully agree with Gotcha here (for what it is worth). I'd love to see the Plone community moving towards pytest at some point and this might be the first step.

**Comment by mauritsvanrees** [comment]
I use `pytest` as test runner in `i18ndude`. Strange: apparently I only use it in [`tox.ini`](https://github.com/collective/i18ndude/blob/master/tox.ini), not in `.travis.yml`. There is room for improvement I see... Anyway, the change was [here](https://github.com/collective/i18ndude/commit/063eaeac31420b81e9e45fc7e5c2b67b84504d8f#diff-b91f3d5bd63fcd17221b267e851608e8), where I replaced the test buildout with just running pip. This seemed to mean that `zope.testrunner` could no longer be used. Maybe I assumed wrong there. But py.test is working fine there, admittedly for a project that is pure Python, using no Plone code.

I also used py.test in a side project (replacement for buildout) that never got past the toy project stage. Its [tests](https://github.com/mauritsvanrees/configcook/tree/master/src/configcook/tests) are fully done with py.test, including fixtures, and only bare `assert` statements. I was quite happy with `py.test` here.

So: fine to try this out for Plone projects, probably first add-ons.

**Comment by icemac** [comment]
I have never seen this project although I use `gocept.pytestlayer` regularly in union.cms. So removing me from the reviewers list.

**Pull request merged**
