### PR TITLE
Add files.pythonhosted.org to allow-hosts in Plone 6

### PR DESCRIPTION
**Pull request by wesleybl**
In some cases, files are found there. See:

https://github.com/plone/plone.autoinclude/issues/18

### CODE REVIEW

**Comment by mauritsvanrees** [comment]
We are currently not using `allow-hosts` anywhere in `buildout.plonetest`, except in `buildout-cache.cfg`, which is a file that we used to recommend for Travis, and which should be irrelevant to current Plone versions (5.2, 6.0).

Setting it now, would mean that only files from pypi.org and files.pythonhosted.org can get downloaded. This will break any buildout config that tries to download for example varnish, or that tries to download a development package from https://dist.plone.org/release/6.0-dev

I think the real problem is that you have an `allow-hosts` in your `~/.buildout/default.cfg` and it is missing the pythonhosted domain. You should add it there.

**Comment by wesleybl** [comment]
> or that tries to download a development package from https://dist.plone.org/release/6.0-dev

https://dist.plone.org/release/6.0-dev is actually being used? I see you are creating all alpha releases in pypi

**Comment by wesleybl** [comment]
> I think the real problem is that you have an allow-hosts in your ~/.buildout/default.cfg

I do not have. I think the default is just `pypi.org`. For me it makes sense that the default is also `files.pythonhosted.org`. Does that make sense to you? Should we open an issue in the `buildout`?

**Comment by mauritsvanrees** [comment]
No, the [default should be `*`](http://www.buildout.org/en/latest/reference.html?highlight=allow-hosts#buildout-configuration-options).
In coredev we [do have more](https://github.com/plone/buildout.coredev/blob/6.0/core.cfg#L8-L16).

**Comment by wesleybl** [comment]
> No, the [default should be *](http://www.buildout.org/en/latest/reference.html?highlight=allow-hosts#buildout-configuration-options).

If it should be * then the buildout is having some problem since I didn't set `allow-hosts` and it only worked after I added `files.pythonhosted.org`

@gotcha do you know anything?

**Comment by mauritsvanrees** [comment]
> https://dist.plone.org/release/6.0-dev is actually being used? I see you are creating all alpha releases in pypi

Yes, it is used, for example here:
https://github.com/plone/plone.namedfile/blob/master/requirements-60.txt

The alpha releases indeed go to PyPI. But I uploaded some pre-alpha / development versions here. I might be tempted to upload another such version of CMFPlone one of these days.

**Comment by mauritsvanrees** [comment]
To debug allow-hosts, I would suggest as first step: `bin/buildout annotate | grep -C10 allow-hosts`

**Comment by wesleybl** [comment]
> But I uploaded some pre-alpha / development versions here.

And does it make sense to `buildout.plonetest` to have access to these versions? Should we keep https://dist.plone.org/release/6.0-dev here?

**Comment by mauritsvanrees** [comment]
> And does it make sense to buildout.plonetest to have access to these versions? Should we keep https://dist.plone.org/release/6.0-dev here?

buildout.plonetest does not need the current package distributions that are there. But I do update the `versions.cfg` and `constraints.txt` sometimes: it should be the same as the previous alpha release, plus a few newer versions. If wanted, add-ons can test against that.

**Comment by wesleybl** [comment]
> To debug allow-hosts, I would suggest as first step: bin/buildout annotate | grep -C10 allow-hosts

I commented out the `allow-hosts` I entered to work and run the command you suggested. See that * appears. But even then it only worked after I added `allow-hosts`.

```bash
$ bin/buildout annotate | grep -C10 allow-hosts
location= ${buildout:backups-dir}/backups
    base.cfg
recipe= collective.recipe.backup
    base.cfg
snapshotlocation= ${buildout:backups-dir}/snapshotbackups
    base.cfg

[buildout]
abi-tag-eggs= true
    /home/user/.buildout/default.cfg
allow-hosts= *
    DEFAULT_VALUE
allow-picked-versions= true
    DEFAULT_VALUE
allow-unknown-extras= false
    DEFAULT_VALUE
backups-dir= ${buildout:var-dir}
    buildout.cfg
bin-directory= bin
    DEFAULT_VALUE
deprecation-warnings= off
```

**Comment by wesleybl** [comment]
Well I removed the whl and egg and ran the buildout again. Now he was able to download the package and finish the buildout. Maybe it was some temporary instability.

Thank you @mauritsvanrees !

**Comment by mauritsvanrees** [comment]
Mystery solved, but still a mystery. ;-)

**Pull request closed without merging**
